require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  NewCops: disable
  Exclude:
    - 'db/schema.rb'
    - 'config/routes.rb'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'Guardfile'

Metrics/AbcSize:
  Max: 50

# For specs
Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'

# The guiding principle of classes is SRP, SRP can't be accurately measured by LoC
Metrics/ClassLength:
  Max: 1500

# The guiding principle of classes is SRP, SRP can't be accurately measured by LoC
Metrics/CyclomaticComplexity:
  Max: 11

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 25
  Exclude:
    - '**/migrate/*'

# Commonly used screens these days easily fit more than 80 characters.
Layout/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
  EnforcedStyle: line_count_based
  FunctionalMethods:
    - before
    - let
    - let!
    - subject
    - watch
    - expect

Style/NumericLiterals:
  MinDigits: 6

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/Documentation:
  Exclude:
    - '**/migrate/*'

Style/HashTransformValues:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/**/**/*'
Style/SymbolProc:
  Enabled: false
