language: ruby
rvm:
 - "2.1.6"
 - "2.2.4"
 - "2.3.0"

script: bundle exec rspec spec

addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 17486efa0f84b7c23a3c56ac04a9a40f3ec00ccc7761475118d811cae1ed3a4c

before_script:
  - psql -c 'create database stall_test_test;' -U postgres
  - bundle exec rake db:schema:load RAILS_ENV=test
